In [4]:
import pandas as pd
import numpy as np

# Create multiple DataFrames (you can add more as needed)
data1 = {
    'mon': [0, 0, 0, 1, 0, 0, 0],
    'tue': [0, 0, 0, 0, 0, 0, 0],
    'wed': [1, 1, 1, 0, 0, 0, 1],
    'thu': [1, 0, 0, 1, 0, 0, 0],
    'fri': [1, 1, 1, 1, 1, 1, 1]
}

data2 = {
    'mon': [0, 1, 0, 0, 0, 0, 0],
    'tue': [0, 0, 0, 0, 0, 0, 0],
    'wed': [0, 0, 1, 1, 1, 0, 0],
    'thu': [1, 0, 0, 0, 0, 1, 0],
    'fri': [0, 1, 0, 0, 0, 0, 1]
}

df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)

# Convert DataFrames to NumPy arrays
array1 = df1.to_numpy()
array2 = df2.to_numpy()

# Perform element-wise addition
result_array = array1 + array2

# Convert the result back to a DataFrame (if needed)
result_df = pd.DataFrame(result_array, columns=df1.columns)

# Print the result
print("Resulting DataFrame:")
print(result_df)


Resulting DataFrame:
   mon  tue  wed  thu  fri
0    0    0    1    2    1
1    1    0    1    0    2
2    0    0    2    0    1
3    1    0    1    1    1
4    0    0    1    0    1
5    0    0    0    1    1
6    0    0    1    0    2


In [14]:
import pandas as pd
import numpy as np

# Define a function to validate each value
def validate_value(value):
    if value in [0, 1] and isinstance(value, int):
        return True
    return False

# Create multiple DataFrames (you can add more as needed)
data1 = {
    'mon': [0, 0, 0, 1, 0, 0, 0],
    'tue': [0, 0, 0, 0, 0, 0, 0],
    'wed': [1, 'a', 1, 0, 0, 0, 1],
    'thu': [1, 0, 0, 1, 0, 0, 0],
    'fri': [1, 1, 1, 1, 1, 1, 1]
}

data2 = {
    'mon': [0, 1, 0, 0, 0, 0, 0],
    'tue': [0, 0, 0, 0, 0, 0, 0],
    'wed': [0, 3, 1, 1, 1, 0, 0],
    'thu': [1, 0, 0, 0, 0, 1, 0],
    'fri': [0, 1, 0, 0, 0, 0, 1]
}

df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)

# Check if each value belongs to {0, 1} and is an integer
is_valid1 = df1.applymap(validate_value)
is_valid2 = df2.applymap(validate_value)

if is_valid1.all().all():
    print("All values in the DataFrames are valid (belong to {0, 1} and are integers).")
else:
    print("There are invalid values in the DataFrames.")

if is_valid2.all().all():
    print("All values in the DataFrames are valid (belong to {0, 1} and are integers).")
else:
    print("There are invalid values in the DataFrames.")
# Convert DataFrames to NumPy arrays
array1 = df1.to_numpy()
array2 = df2.to_numpy()
print(df1)
print(array1)
# Perform element-wise addition
result_array = array1 + array2

# Convert the result back to a DataFrame (if needed)
result_df = pd.DataFrame(result_array, columns=df1.columns)

# Print the result
print("Resulting DataFrame:")
print(result_df)


There are invalid values in the DataFrames.
There are invalid values in the DataFrames.
   mon  tue wed  thu  fri
0    0    0   1    1    1
1    0    0   a    0    1
2    0    0   1    0    1
3    1    0   0    1    1
4    0    0   0    0    1
5    0    0   0    0    1
6    0    0   1    0    1
[[0 0 1 1 1]
 [0 0 'a' 0 1]
 [0 0 1 0 1]
 [1 0 0 1 1]
 [0 0 0 0 1]
 [0 0 0 0 1]
 [0 0 1 0 1]]


TypeError: can only concatenate str (not "int") to str

In [9]:
import pandas as pd

# Create a list of DataFrames with the same shape
dfs = [pd.DataFrame({'A': [0, 0, 1], 'B': [1, 0, 0], 'C': [1, 1, 0]}).to_numpy(),
       pd.DataFrame({'A': [1, 0, 0], 'B': [0, 0, 1], 'C': [1, 0, 0]}).to_numpy(),
       pd.DataFrame({'A': [0, 1, 0], 'B': [0, 0, 1], 'C': [0, 0, 0]}).to_numpy()]

# Iterate through the DataFrames and check for the presence of 1
print(dfs[0])
row = 0
col = 'C'
def check_people(col, row, arrays):
    name_list = []
    for i, arr in enumerate(arrays):
        if arr[row, col] == 1:
            print(f"DataFrame {i}, Row {row}, Column {col} contains 1")
            name_list.append(i)

    return name_list    
check_people(2, 0, dfs)

[[0 1 1]
 [0 0 1]
 [1 0 0]]
DataFrame 0, Row 0, Column 2 contains 1
DataFrame 1, Row 0, Column 2 contains 1


[0, 1]

In [1]:
def filter_dict_by_keys(input_dict, key_list):
    return {key: input_dict[key] for key in key_list if key in input_dict}

# Example usage:
input_dict = {
    'a': 1,
    'b': 2,
    'c': 3,
    'd': 4,
    'e': 5
}

keys_to_keep = ['a', 'c', 'e']

filtered_dict = filter_dict_by_keys(input_dict, keys_to_keep)
print(filtered_dict)


{'a': 1, 'c': 3, 'e': 5}
